# Generated by Django 4.1.4 on 2022-12-28 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homebg', models.ImageField(upload_to='allimages')),
                ('bgtitle', models.TextField(max_length=1000)),
                ('homebtn', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navitem_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navitem_1', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navitem_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navitem_2', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navitem_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navitem_3', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navitem_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navitem_4', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navitem_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navitem_5', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navitem_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navitem_6', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navsubitem_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navsubitem_1', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navsubitem_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navsubitem_2', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navsubitem_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navsubitem_3', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navsubitem_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navsubitem_4', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navsubitem_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navsubitem_5', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navsubitem_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navsubitem_6', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navlogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navlogo', models.TextField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
