# Generated by Django 4.1.4 on 2022-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('latest_img', models.ImageField(upload_to='allimages')),
            ],
        ),
        migrations.CreateModel(
            name='LeftContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('copyRight', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeftMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('descriptions', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='homebg',
            name='homebtn',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem_1',
            name='navitem_1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem_2',
            name='navitem_2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem_3',
            name='navitem_3',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem_4',
            name='navitem_4',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem_5',
            name='navitem_5',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem_6',
            name='navitem_6',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navlogo',
            name='navlogo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navsubitem_1',
            name='navsubitem_1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navsubitem_2',
            name='navsubitem_2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navsubitem_3',
            name='navsubitem_3',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navsubitem_4',
            name='navsubitem_4',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navsubitem_5',
            name='navsubitem_5',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navsubitem_6',
            name='navsubitem_6',
            field=models.TextField(max_length=100),
        ),
    ]
