# Generated by Django 4.1.4 on 2022-12-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_latest_leftcontact_leftmenu_alter_homebg_homebtn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastestPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latestImg', models.ImageField(upload_to='allimages')),
            ],
        ),
        migrations.CreateModel(
            name='Latesttitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Latest',
        ),
    ]
