# Generated by Django 4.1.4 on 2022-12-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clientlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('category', models.CharField(choices=[('seo', 'SEO'), ('WebDesign', 'WEBDESIGN'), ('SocialMediaMarketing', 'SOCIALMEDIAMARKETING'), ('WebDevelopment', 'WEBDEVELOPMENT'), ('EmailMarketing', 'EMAILMARKETING'), ('ADsManagement', 'ADMANAGEMENT')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesBtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicetitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('subtitle', models.TextField(max_length=100)),
                ('subtitle1', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WhatWedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('servicesbtn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.servicesbtn')),
                ('title1', models.TextField(max_length=100)),
                ('title2', models.TextField(max_length=100)),
                ('description1', models.TextField(max_length=250)),
                ('description2', models.TextField(max_length=250)),
                ('img', models.ImageField(upload_to='allimages')),
            ],
            bases=('app.servicesbtn',),
        ),
    ]
